#moduły
ExampleModule: false
Voting: false
NewbieProtect: false
Frakcjonawka: false
Stats: false
Bets: false
BlackJack: true
OwnHorse: true
LocalChat: true
Bandage: true
DynmapPrinting: false

#database connection
#Pamietaj aby nie wlaczac modulow zwiazanych z baza danych, bez poprawnego polaczenia.
DatabaseEnabled: false
host: "127.0.0.1"
port: 3306
database: 'jbwmstats'
username: 'root'
password: ''