#moduły
ExampleModule: false
Voting: false
NewbieProtect: false
Frakcjonawka: true
Stats: true
Bets: true

#database connection
#Pamietaj aby nie wlaczac modulow zwiazanych z baza danych, bez poprawnego polaczenia.
DatabaseEnabled: false
host: "127.0.0.1"
port: 3306
database: 'jbwmstats'
username: 'root'
password: ''