name: JbwmMiscellaneous
version: ${project.version}
main: koral.jbwmmiscellaneous.JbwmMiscellaneous
api-version: 1.16
authors: [ koral ]
description: Miscellaneous
commands:
  newbie:
  vote:
    description: vote day/night or force
    aliases: glosowanie